version: '3.8'
services:
  mongo-container:
    image: mongo:latest
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongo-admin
        - MONGO_INITDB_ROOT_PASSWORD=mongo-admin
    volumes:
    - /mongodb/data:/data/db
    ports:
      - "27017:27017"
    command: mongod
    restart: unless-stopped
